### ISSUE TITLE
Release Terms 2.0 era for General

### ISSUE THREAD

**Issue by Nosferican** [JuliaStats/StatsModels.jl#100]
Is there anything outstanding for a release with Terms 2.0?

**Comment by Nosferican** [comment]
@kleinschmidt Any update on this?

**Comment by kleinschmidt** [comment]
I won't have time to look at this in depth for a few more weeks (late May/early June); there are a few bugs to fix before I'm comfortable tagging a release (#95 and #97 regarding `apply_schema`) and I'd like to have another look at how continuous terms are converted to numerical form (currently they're forced to `FLoat64` which doesn't make sense since some models might want to consume other numeric types, and see the related issues in JuliaStats/Survival.jl#10)

**Comment by Nosferican** [comment]
Let me know if there is an update on the timeline... I gave up on trying to have code coverage and documentation simultaneously while having a package checked out. I will keep working on my project with the check out version and will deploy with docs when Terms 2 gets a release.

**Comment by kleinschmidt** [comment]
@JuliaRegistrator register()
