### ISSUE TITLE
Interactions of the form x&id

### ISSUE THREAD

**Issue by matthieugomez** [JuliaStats/StatsModels.jl#140]
I have an categorical variable id with N categories. 
Putting an interaction of the form x&id in the formula gives a matrix with N- 1 rows but it seems like the matrix should return N rows, since x is not included in the formula.
```julia
using DataFrames, StatsModels
df = DataFrame(y = [1, 2, 3], x = [2, 3, 4], id = categorical([1, 2, 3]))
f = @formula(y~ x&id)
f_schema = apply_schema(f, schema(f, df))
modelmatrix(f_schema, df)
```

**Comment by matthieugomez** [comment]
One possibility is to add `StatisticalModel` as an argument of `apply_schema` but it does not work with only the RHS formula for some reason
```
using DataFrames, StatsModels
df = DataFrame(y = [1, 2, 3], x = [2, 3, 4], id = categorical([1, 2, 3]))
f = @formula(y~ x&id)
f_schema = apply_schema(f, schema(f, df), StatisticalModel)
f_schema = apply_schema(f.rhs, schema(f.rhs, df), StatisticalModel)
```

**Comment by kleinschmidt** [comment]
The way that "full rank" logic is handled is by dispatching on the `FullRank` schema wrapper:

```
apply_schema(f.rhs, StatsModels.FullRank(schema(f.rhs, df)))
```

(you can include `StatisticalModel` for the context or not, I don't think it matters at that point...)

The wrapper is used both for dispatch but also for the book-keeping that's necessary to tell whether something should be promoted to "full dummy coding".  The reason using StatisticalModel as the context works for the whole formula but not for the RHS is that the wrapper is created in the `apply_schema(::FormulaTerm, ::Schema, <:StatisticalModel)` method, because the book-keeping needs to be at the level of the whole formula: https://github.com/JuliaStats/StatsModels.jl/blob/master/src/schema.jl#L258-L277  But there's nothing stopping you from creating your own whenever you please like the example above :)

I guess this could be documented better.....

**Comment by matthieugomez** [comment]
Oh this explains a lot. I never realized there was a different method for `apply_scheme` for FormulaTerm vs other term.  I actually also had issues understanding when the intercept was kept and when MatrixTerms was used...
Is there a way to make this simpler? Maybe by writing a similar function for `Union{AbstractTerm, TupleTerm}`?

**Comment by matthieugomez** [comment]
Or maybe the best solution would be to allow Formulas where the left hand side is empty.

**Comment by kleinschmidt** [comment]
Currently the best way to do that is to use `0~...` (see #139 also)
