### ISSUE TITLE
Missing method for fe(:a) * fe(:d) is missing when using term()

### ISSUE THREAD

**Issue by IljaK91** [JuliaStats/StatsModels.jl#258]
Hi everyone, I was sent over from FixedEffectModels.jl as the problem seems to stem from StatsModels.jl

Here is the link to the thread: https://github.com/FixedEffects/FixedEffectModels.jl/issues/206

Here is the original issue:

The following throws an error when using *

```
df = DataFrame(a=rand(10), b=rand(10), c=[1, 1, 1, 0, 0, 0, 0, 0, 0, 0], d=[0,0,0,0,0, 1, 1, 1, 1, 1 ])

reg(df, term(:a) ~ term(:b) + fe(:c) * fe(:d)) # This throws an error
reg(df, term(:a) ~ term(:b) + fe(:c) & fe(:d)) # This works
reg(df, term(:a) ~ term(:b) + fe(:c) + fe(:d) + fe(:c) & fe(:d)) # This works
```

error message:

```
ERROR: MethodError: no method matching *(::FixedEffectModels.FixedEffectTerm, ::FixedEffectModels.FixedEffectTerm)
Closest candidates are:
  *(::Any, ::Any, ::Any, ::Any...) at C:\Users\kantorov\.julia\juliaup\julia-1.7.3+0~x64\share\julia\base\operators.jl:655
  *(::Union{MathOptInterface.ScalarAffineFunction{T}, MathOptInterface.ScalarQuadraticFunction{T}, MathOptInterface.VectorAffineFunction{T}, MathOptInterface.VectorQuadraticFunction{T}}, ::T) where T at C:\Users\kantorov\.julia\packages\MathOptInterface\AiEiQ\src\Utilities\functions.jl:3270
  *(::ChainRulesCore.AbstractThunk, ::Any) at C:\Users\kantorov\.julia\packages\ChainRulesCore\16PWJ\src\tangent_arithmetic.jl:125
  ...
Stacktrace:
 [1] top-level scope
   @ c:\Users\kantorov\Desktop\mwe.jl:13
```

**Comment by kleinschmidt** [comment]
Among other things, this is fixed by #183 IIRC.

**Comment by kleinschmidt** [comment]
As for why, it's because the formula syntax (distributed/associative rules for `+` and `&`, `*` expansion) are handled inside the `@formula` macro currently, and not at runtime.  I decided at some point that it was better to have _one_ source of truth for how these expansions worked or else you're in danger of getting different results from superficially similar formulae (at run-time vs. `@formula`).  #183 changes that one source of truth to be the run-time operators themselves, so _everything_ is handled by the methods like `*(::AbstractTerm, ::AbstractTerm)`

**Comment by matthieugomez** [comment]
Thanks! This can be closed now — this code snippet no longer throws an error with the latest version of FixedEffectModels.
