### ISSUE TITLE
Order of terms has flipped when using `+`

### ISSUE THREAD

**Issue by rikhuijzer** [JuliaStats/StatsModels.jl#289]
In one of the recent releases, the order of terms has flipped when constructing a term via the plus operator.

In a recent version with some StatsModels 0.7 version:
```julia
julia> form = GLM.Term(:y) ~ GLM.term(:x) + GLM.term(1)
FormulaTerm
Response:
  y(unknown)
Predictors:
  1
  x(unknown)
```
While in a StatsModels 0.6 version:
```julia
julia> form = GLM.Term(:y) ~ GLM.term(:x) + GLM.term(1)
FormulaTerm
Response:
  y(unknown)
Predictors:
  x(unknown)
  1
```
Note that the order of the predictors has reversed. There is probably a good reason for this change, but it appears a bit counterintuitive now.

**Comment by kleinschmidt** [comment]
Ah yeah this is a consequence of making both the run-time and `@formula` constructed terms go through the same code path.  See also #286 which was the opposite issue: previously in a `@formula`, constant terms always got sorted before everything else but 0.7 introduced a bug that changed that.

If you really need this kind of control over term ordering, it's probably better to use the constructors for `FormulaTerm` et al. directly rather than relying on the operators, since those are now going to (in all likelihood) always behave like they do inside `@formula`.

**Comment by rikhuijzer** [comment]
Okay so having the lowest order terms first is as expected and in-line with the rest. That means that we can close this 👍 Thanks for taking a look
