### ISSUE TITLE
Calling `apply_schema` twice should not be an error

### ISSUE THREAD

**Issue by oxinabox** [JuliaStats/StatsModels.jl#97]
MWE:

```
using StatsModels, DataFrames

f = @formula(y ~ 1 + a + b + c + b&c)
df = DataFrame(y = rand(9), a = 1:9, b = rand(9), c = repeat(["d","e","f"], 3))
f = apply_schema(f, schema(f, df))
f = apply_schema(f, schema(f, df))
```

The last line errors with

```
MethodError: no method matching concrete_term(::ContinuousTerm{Float64}, ::NamedTuple{(:y, :a, :b, :c),Tuple{Array{Float64,1},Array{Int64,1},Array{Float64,1},Array{String,1}}}, ::Dict{Symbol,Any})
```

**Comment by kleinschmidt** [comment]
I think the way to fix this is to add the missing methods for `concrete_term` and `apply_schema`.  I think the `apply_schema` ones might already be there because of `setcontrasts!` (which requires replacing one concrete term with another), so all that's needed might be a method for `concrete_term`.  PR welcome!
